Us fixvariables s04
WildCodeSchool-2024-02/JS-bdx-0224-P3-street_art_hunter pull request #13
Opened 2024-06-27 14:55 UTC by Dinosaure7

2024-06-27 15:21 UTC, Alice-Berthelot approved these changes

2024-06-28 06:55 UTC, Alice-Berthelot requested changes
The font imported should be "Sedgwick Ave Display", not "Sedgwick Ave"

2024-06-28 09:22 UTC, Alice-Berthelot approved these changes

2024-06-28 09:22 UTC, sorrento974 approved these changes

2024-06-28 09:46 UTC, KevinDavoust approved these changes

2024-06-28 09:46 UTC, merged