Fix us03 s03 register
WildCodeSchool-2024-02/JS-bdx-0224-P3-street_art_hunter pull request #17
Opened 2024-07-01 19:43 UTC by Delgorithm

2024-07-02 13:33 UTC, Alice-Berthelot requested changes

2024-07-02 13:33 UTC, Alice-Berthelot commented on client/src/App.jsx
remove main

2024-07-02 13:33 UTC, Alice-Berthelot commented on client/src/assets/images/mockup.png
change mockups

2024-07-02 13:33 UTC, Alice-Berthelot commented on client/src/pages/Login.jsx
add link in img

2024-07-02 13:33 UTC, Alice-Berthelot commented on client/src/pages/Register.jsx
add link in img

2024-07-02 13:33 UTC, Alice-Berthelot commented on client/src/styles/RegisterLogin.css
utiliser les variables de couleur

2024-07-02 13:33 UTC, Alice-Berthelot commented on server/database/models/ArtRepository.js
keep the initial SQL request:

SELECT ${this.table}.id, ${this.table}.latitude, ${this.table}.longitude, p.image FROM ${this.table} JOIN picture as p ON p.${this.table}_id=art.id

2024-07-02 13:33 UTC, Alice-Berthelot commented on server/database/models/ItemRepository.js
We don't need this repo (maybe check if it is declared in tables.js)

2024-07-02 13:33 UTC, Alice-Berthelot commented on server/database/tables.js
See if ITemRepository is needed

2024-07-02 13:37 UTC, sorrento974 approved these changes

2024-07-02 13:37 UTC, sorrento974 commented on client/src/App.jsx
warning : main

2024-07-02 13:37 UTC, sorrento974 commented on client/src/assets/images/mockup.png
mockup's navbar have changed

2024-07-02 13:37 UTC, sorrento974 commented on server/app/controllers/userAction.js
add a "s" to userAction like this : userActions

2024-07-02 13:37 UTC, sorrento974 commented on server/database/fixtures/RegisterSeeder.js
please delete it

2024-07-02 16:43 UTC, Alice-Berthelot approved these changes

2024-07-03 13:09 UTC, Elea641 requested changes

2024-07-03 13:09 UTC, Elea641 commented on server/app/controllers/authActions.js
> +    const user = await tables.user.readByEmailWithPassword(req.body.email);
implémenter un middleware

2024-07-03 13:09 UTC, Elea641 commented on server/app/middlewares/verifyAuth.js
> +const hashPassword = async (req, res, next) => {
pour moi implémente deux middlewares ici pour ne pas avoir plusieurs fonctions mais un enchaînement de middlewares

2024-07-03 13:09 UTC, Elea641 commented on server/app/middlewares/verifyAuth.js
> +const hashPassword = async (req, res, next) => {
pour moi implémente deux middlewares ici pour ne pas avoir plusieurs fonctions mais un enchaînement de middlewares

2024-07-03 20:28 UTC, Delgorithm commented on server/database/models/ItemRepository.js
It is done my Queen

2024-07-06 15:27 UTC, Alice-Berthelot approved these changes

2024-07-08 07:41 UTC, Elea641 requested changes

2024-07-08 07:41 UTC, Elea641 commented on client/src/main.jsx
> +    path: "/",
ligne à supprimer path:"/"

2024-07-08 07:41 UTC, Elea641 commented on client/src/main.jsx
>  async function fetchApi(url) {
déplacer la logique dans un service

2024-07-08 12:19 UTC, KevinDavoust approved these changes

2024-07-08 12:19 UTC, merged