Fix us26 s02 navbar
WildCodeSchool-2024-02/JS-bdx-0224-P3-street_art_hunter pull request #19
Opened 2024-07-09 12:26 UTC by Delgorithm

2024-07-09 14:23 UTC, Alice-Berthelot approved these changes

2024-07-09 15:17 UTC, sorrento974 approved these changes

2024-07-10 08:54 UTC, KevinDavoust requested changes

2024-07-10 08:54 UTC, KevinDavoust commented on client/src/components/NavBar.jsx
> +          src="./src/assets/images/new-logo-pixhunt-Photoroom.webp"
import pas comme pour les autres images

2024-07-10 08:54 UTC, KevinDavoust commented on client/src/components/NavBar.jsx
> +            <span>Accueil</span>
changer tout ça par des balises figure avec le texte en figcaption et pas en span

2024-07-10 08:54 UTC, KevinDavoust commented on client/src/components/NavBar.jsx
> +            <span>Classement</span>
pareil

2024-07-10 08:54 UTC, KevinDavoust commented on client/src/components/NavBar.jsx
> +            <span className="spanInscription">Inscription</span>
ici aussi

2024-07-10 10:31 UTC, KevinDavoust requested changes

2024-07-10 10:31 UTC, KevinDavoust commented on client/src/components/NavBar.jsx
>        {isOpen ? (
privilégier un affichage avec &&, plutôt qu'une ternaire avec null dans le else

2024-07-10 11:08 UTC, merged