Us2 s03 instructions modal
WildCodeSchool-2024-02/JS-bdx-0224-P3-street_art_hunter pull request #21
Opened 2024-07-09 13:49 UTC by Dinosaure7

2024-07-09 14:13 UTC, Delgorithm requested changes

2024-07-09 14:13 UTC, Delgorithm commented on client/index.html
>      <script type="module" src="/src/main.jsx"></script>
You should not touch "index.html" for that

2024-07-09 14:13 UTC, Delgorithm commented on client/src/App.jsx
> +  const modalContentEl = document.getElementById("modal-content");
We don't use this DOM element like this in React and JSX

2024-07-09 14:13 UTC, Delgorithm commented on client/src/App.jsx
> +  useEffect(() => {}, [showModal, modalContentEl]);
What is the purpose of it ?

2024-07-09 14:13 UTC, Delgorithm commented on client/src/App.jsx
>        <Navbar />
You should simply add all of it in "Home.jsx" instead of adding it in "App.jsx"

2024-07-09 14:13 UTC, Delgorithm commented on client/src/components/ModalContent.jsx
> +        </button>
What does "&times;" even mean ?
You can use a self close balise "<button />"

2024-07-09 14:13 UTC, Delgorithm commented on client/src/components/ModalContent.jsx
> +          href="#"
You don't have to add "href='#'"

2024-07-09 14:13 UTC, Delgorithm commented on client/src/styles/App.css
>    list-style: none;
You don't have to duplicate the code

2024-07-09 14:13 UTC, Delgorithm commented on client/src/styles/ModalContent.css
> +  transform: translate(-50%, -50%);
I don't know why you use "50%" and "transform translate" at the same time

2024-07-09 14:13 UTC, Delgorithm commented on client/src/styles/ModalContent.css
> +  font-size: 22px;
You have to use "rem" instead of "px"

2024-07-09 14:13 UTC, Delgorithm commented on client/src/styles/ModalContent.css
> +  z-index: 1000;
Going to the moon ?

2024-07-09 14:13 UTC, Delgorithm commented on client/src/styles/ModalContent.css
> +  font-size: 16px;
You should use "rem" instead of "px"

2024-07-09 14:13 UTC, Delgorithm commented on client/src/styles/ModalContent.css
> +  padding: 1rem 1rem 0.5rem 1rem;
Go simply for "1rem"

2024-07-09 14:13 UTC, Delgorithm commented on client/src/styles/ModalContent.css
> +    font-size: 32px;
We use "rem" instead of "px"

2024-07-09 14:13 UTC, Delgorithm commented on client/src/styles/ModalContent.css
> +}
Furthemore, the responsive is not "effective" you should work on it more

2024-07-10 06:36 UTC, Dinosaure7 commented on client/index.html
>      <script type="module" src="/src/main.jsx"></script>
As we discussed this is how it is done :)

2024-07-10 06:37 UTC, Dinosaure7 commented on client/src/App.jsx
> +  const modalContentEl = document.getElementById("modal-content");
This is part of the setup, using portal and modal react element, we can use a dom element. I al ok if you have suggestions.

2024-07-10 06:39 UTC, Dinosaure7 commented on client/src/App.jsx
> +  useEffect(() => {}, [showModal, modalContentEl]);
The whole setting is to create the portal/modal and get the ModalContent component.

2024-07-10 06:41 UTC, Dinosaure7 commented on client/src/App.jsx
>        <Navbar />
We have fixed things with an assistant teacher, Elea, and the result was to delete the InstrutionModal component and set the whole logic in App.jsx.

2024-07-10 06:42 UTC, Dinosaure7 commented on client/src/components/ModalContent.jsx
> +        </button>
The is for the close button, the modal is set to close on its own after 8 seconds but what if the user wants to close it before that! Hence the x.

2024-07-10 06:43 UTC, Dinosaure7 commented on client/src/styles/ModalContent.css
> +  z-index: 1000;
lol

2024-07-10 06:43 UTC, Dinosaure7 commented on client/src/styles/ModalContent.css
> +  font-size: 16px;
sure

2024-07-10 06:44 UTC, Dinosaure7 commented on client/src/styles/ModalContent.css
> +  padding: 1rem 1rem 0.5rem 1rem;
ok

2024-07-10 06:44 UTC, Dinosaure7 commented on client/src/styles/ModalContent.css
> +    font-size: 32px;
ok

2024-07-10 06:44 UTC, Dinosaure7 commented on client/src/styles/ModalContent.css
> +}
Not perfect, true

2024-07-16 13:18 UTC, Alice-Berthelot requested changes

2024-07-16 13:18 UTC, Alice-Berthelot commented on client/index.html
>      <script type="module" src="/src/main.jsx"></script>
Seen with Elea apparently

2024-07-16 13:18 UTC, Alice-Berthelot commented on client/src/App.jsx
> +  const modalContentEl = document.getElementById("modal-content");
why is the modal called "modalContentEl" ?

2024-07-16 13:18 UTC, Alice-Berthelot commented on client/src/styles/ModalContent.css
> +  z-index: 1000;
z-index could be reduced, couldn't it ?

2024-07-16 13:18 UTC, Alice-Berthelot commented on client/src/styles/ModalContent.css
> +  font-size: 16px;
Delgorithm's comment should be taken into account

2024-07-16 13:18 UTC, Alice-Berthelot commented on client/src/styles/ModalContent.css
> +  padding: 1rem 1rem 0.5rem 1rem;
Delgorithm's comment should be taken into account

2024-07-16 13:18 UTC, Alice-Berthelot commented on package.json
you should check with Yoann for this one

2024-07-19 13:37 UTC, closed without merging