adding contact page + button back
WildCodeSchool-2024-02/JS-bdx-0224-P3-street_art_hunter pull request #22
Opened 2024-07-09 14:50 UTC by sorrento974

2024-07-09 14:55 UTC, Delgorithm requested changes

2024-07-09 14:55 UTC, Delgorithm commented on client/src/styles/Contact.css
> +  font-family: "Atkinson Hyperlegible", sans-serif;
You have to change the variable with the ones in the root

2024-07-09 14:55 UTC, Delgorithm commented on client/src/styles/Contact.css
> +  font-weight: bold;
You'll have to change the "px" to "rem"

2024-07-09 14:55 UTC, Delgorithm commented on client/src/styles/Contact.css
> +  border: 1px solid #ccc;
You'll have to change the "px" to "rem"

2024-07-09 14:55 UTC, Delgorithm commented on client/src/styles/Contact.css
> +  color: #bbb;
You have to change the variable with the ones in the root

2024-07-09 14:55 UTC, Delgorithm commented on client/src/styles/Contact.css
> +}
You'll have to change the "px" to "rem"

2024-07-09 14:55 UTC, Delgorithm commented on client/src/styles/Contact.css
> +  font-family: "Atkinson Hyperlegible", sans-serif;
You have to delete the comment

2024-07-09 14:55 UTC, Delgorithm commented on client/src/styles/Contact.css
> +  scale: 0.95;
You have to delete the comment

2024-07-09 14:55 UTC, Delgorithm commented on client/src/styles/Contact.css
> +}
You'll have to change the "px" to "rem"

2024-07-09 16:43 UTC, Alice-Berthelot requested changes

2024-07-09 16:43 UTC, Alice-Berthelot commented on client/src/styles/Contact.css
> +  margin-bottom: 15px;
there is a px that should be transformed into rem (line 34)

2024-07-09 16:43 UTC, Alice-Berthelot commented on client/src/styles/Contact.css
> +  border: 1px solid #bbb;
you should choose colors that are in our variables, not #bbb

2024-07-09 16:43 UTC, Alice-Berthelot commented on client/src/styles/Contact.css
>    color: #bbb;
you should choose colors that are in our variables, not #bbb

2024-07-09 16:43 UTC, Alice-Berthelot commented on client/src/styles/Contact.css
>    color: red;
you should choose colors that are in our variables, not #bbb

2024-07-09 16:43 UTC, Alice-Berthelot commented on client/src/styles/Contact.css
>    border-radius: 4px;
the px should be transformed into rem

2024-07-09 16:43 UTC, Alice-Berthelot commented on client/src/styles/Contact.css
> +  border-radius: 10px;
px should be transformed into rem

2024-07-09 16:43 UTC, Alice-Berthelot commented on client/src/styles/Contact.css
> +  border-radius: 4px;
px should be transformed into rem

2024-07-09 16:43 UTC, Alice-Berthelot commented on client/src/styles/Contact.css
> +  background-color: #c0c0c0;
you should pick colours from our variables only

2024-07-10 06:54 UTC, Alice-Berthelot approved these changes

2024-07-10 09:02 UTC, KevinDavoust requested changes

2024-07-10 09:02 UTC, KevinDavoust commented on client/src/pages/Contact.jsx
> +      console.error(e);
rien dans la console

2024-07-10 09:02 UTC, KevinDavoust commented on client/src/pages/Contact.jsx
> +            <div
pas ça zinédine... pas après tout ce que tu as fait.......

2024-07-10 09:02 UTC, KevinDavoust commented on client/src/pages/Contact.jsx
> +        src="./src/assets/images/5ba7c8d79a1de659493719.jpg"
il faudrait importer l'image comme une variable en haut du fichier plutôt que mettre le chemin en dur directement dans src

2024-07-11 07:36 UTC, KevinDavoust requested changes

2024-07-11 07:36 UTC, KevinDavoust commented on client/src/components/BtnGoBack.jsx
> +    <button
vu que ce bouton exécute une redirection, une balise Link serait plus appropriée, et éviterait cette méthode handleClick

2024-07-11 07:36 UTC, KevinDavoust commented on client/src/pages/Contact.jsx
> +          type="button"
le bouton doit être de type submit pour soumettre le formulaire, le type button est réservé pour de simples interactions utilisateur

2024-07-11 08:15 UTC, Alice-Berthelot commented on client/src/pages/Contact.jsx
> +          type="button"
done

2024-07-11 08:18 UTC, Alice-Berthelot requested changes

2024-07-11 08:18 UTC, Alice-Berthelot commented on client/src/components/BtnGoBack.jsx
this button should link to the previous page and not home

2024-07-12 10:02 UTC, merged