footer
WildCodeSchool-2024-02/JS-bdx-0224-P3-street_art_hunter pull request #23
Opened 2024-07-10 08:01 UTC by sorrento974

2024-07-10 09:56 UTC, Delgorithm requested changes

2024-07-10 09:56 UTC, Delgorithm commented on client/src/styles/Footer.css
> +    text-align: center;
You have to use vars from the "root"

2024-07-10 19:29 UTC, Alice-Berthelot approved these changes

2024-07-10 19:31 UTC, Dinosaure7 approved these changes
Seems all good to me

2024-07-11 07:29 UTC, KevinDavoust requested changes

2024-07-11 07:29 UTC, KevinDavoust commented on client/src/components/Footer.jsx
> +        <h2>PixHunt</h2>
les seuls enfants possibles pour un ul sont des li

2024-07-11 07:46 UTC, Alice-Berthelot commented on client/src/components/Footer.jsx
> +        <h2>PixHunt</h2>
done

2024-07-11 09:32 UTC, Elea641 requested changes

2024-07-11 09:32 UTC, Elea641 commented on client/src/components/Footer.jsx
> +        <Link to="/contact" className="link-inline-item">
les li doivent entourer les Link

2024-07-11 10:13 UTC, Alice-Berthelot commented on client/src/components/Footer.jsx
> +        <Link to="/contact" className="link-inline-item">
done

2024-07-11 10:23 UTC, Elea641 approved these changes

2024-07-11 10:23 UTC, merged