Us10 s06 before home
WildCodeSchool-2024-02/JS-bdx-0224-P3-street_art_hunter pull request #34
Opened 2024-07-15 12:10 UTC by sorrento974

2024-07-16 08:07 UTC, Dinosaure7 requested changes
Review the pre-hompage route

2024-07-16 08:07 UTC, Dinosaure7 commented on client/src/main.jsx
> +    path: "/",
the path / is for the home page, you can use /BeforeHome for example for the path of the pre-homepage

2024-07-16 13:07 UTC, Alice-Berthelot requested changes
images about street art should be stocked in server, not client (server > public > assets > images)

2024-07-16 13:11 UTC, Alice-Berthelot requested changes

2024-07-16 13:11 UTC, Alice-Berthelot commented on client/src/main.jsx
> +    path: "/",
yes the path for BeforeHome is "/", however this path "/" has been used until now for our Home page so you should carefully change all the links that point to "/" to "/home" , on all the pages of our application

also BeforeHome is a child of App, so it should be moved down

2024-07-22 08:22 UTC, Dinosaure7 approved these changes

2024-07-22 11:39 UTC, Yoann-Fortin approved these changes

2024-07-22 11:39 UTC, Yoann-Fortin approved these changes

2024-07-22 13:33 UTC, Yoann-Fortin approved these changes

2024-07-22 13:33 UTC, merged