Fix us02 s03 instructions modal
WildCodeSchool-2024-02/JS-bdx-0224-P3-street_art_hunter pull request #41
Opened 2024-07-16 15:05 UTC by sorrento974

2024-07-16 15:24 UTC, Alice-Berthelot approved these changes

2024-07-19 13:19 UTC, Dinosaure7 approved these changes
Looks all good to me
Do not push json from root

2024-07-20 14:37 UTC, Yoann-Fortin requested changes

2024-07-20 14:37 UTC, Yoann-Fortin commented on client/src/components/ModalContent.jsx
> +    <section className="modal">
Dialog tag is require here

2024-07-20 14:37 UTC, Yoann-Fortin commented on client/src/components/ModalContent.jsx
> +      <button type="button" className="close-button" onClick={onClose}>
Aria label is missing

2024-07-20 16:14 UTC, Dinosaure7 commented on client/src/components/ModalContent.jsx
> +      <button type="button" className="close-button" onClick={onClose}>
done

2024-07-22 11:36 UTC, Yoann-Fortin approved these changes

2024-07-22 11:36 UTC, merged