Update README.md
WildCodeSchool-2024-02/JS-bdx-0224-P3-street_art_hunter pull request #45
Opened 2024-07-20 09:43 UTC by sorrento974

2024-07-20 10:15 UTC, Alice-Berthelot requested changes

2024-07-20 10:15 UTC, Alice-Berthelot commented on README.md
> +Urban Art Explorer a pour objectif de faire découvrir et de chasser (en photographiant) les arts urbains, tels que les graffitis et autres œuvres de street art, qui embellissent les murs de la magnif
The app name should be reviewed

2024-07-20 10:15 UTC, Alice-Berthelot commented on README.md
> +Nous espérons que vous apprécierez utiliser Urban Art Explorer autant que nous avons aimé le développer. N'hésitez pas à contribuer, à signaler des bugs ou à suggérer de nouvelles fonctionnalités !
The app name should be reviewed

2024-07-20 12:55 UTC, Alice-Berthelot approved these changes

2024-07-21 13:53 UTC, Delgorithm approved these changes

2024-07-22 07:45 UTC, Dinosaure7 approved these changes

2024-07-23 06:27 UTC, Yoann-Fortin approved these changes

2024-07-23 06:27 UTC, merged