Fix us11 s06 logout
WildCodeSchool-2024-02/JS-bdx-0224-P3-street_art_hunter pull request #48
Opened 2024-07-21 14:08 UTC by sorrento974

2024-07-22 07:53 UTC, Dinosaure7 approved these changes

2024-07-22 14:25 UTC, Alice-Berthelot approved these changes
package-lock à retirer après validation du reste par Yoann
husky remis à jour du initial commit

2024-07-23 06:27 UTC, Yoann-Fortin requested changes

2024-07-23 06:27 UTC, Yoann-Fortin commented on client/src/components/LogoutMobile.jsx
> +        <article className="logout-modal-mobile">
A modal required a dialog tag

2024-07-23 06:27 UTC, Yoann-Fortin commented on client/src/components/NavBar.jsx
> +        <ul className="logout-container">
See comment above

2024-07-23 10:00 UTC, Yoann-Fortin approved these changes

2024-07-23 10:00 UTC, merged