Us25 s02 searchbar
WildCodeSchool-2024-02/JS-bdx-0224-P3-street_art_hunter pull request #5
Opened 2024-06-18 11:16 UTC by Dinosaure7

2024-06-18 16:26 UTC, sorrento974 approved these changes

2024-06-18 16:26 UTC, sorrento974 commented on server/.eslintrc.json
ok si validé par yohan pour la desactivation : "react/jsx-props-no-spreading": "off"

2024-06-18 16:26 UTC, sorrento974 commented on client/src/App.jsx
tu importes deux fois le fichier App.css?

2024-06-18 16:26 UTC, sorrento974 commented on client/src/main.jsx
commentaire inutile :{/* set a provider de leafletGeocoder.jsx? */}

2024-06-18 16:26 UTC, sorrento974 commented on client/tailwind.config.js
commentaire a enlever

2024-06-18 16:26 UTC, sorrento974 commented on server/.eslintrc.json
espace blanc a enlever ligne 2

2024-06-19 06:15 UTC, sorrento974 approved these changes

2024-06-19 06:59 UTC, Alice-Berthelot approved these changes

2024-06-19 06:59 UTC, Alice-Berthelot commented on server/index.js
pourquoi supprimer le ";" ?

2024-06-19 13:41 UTC, Yoann-Fortin requested changes

2024-06-19 13:41 UTC, Yoann-Fortin commented on package.json
Interdit de rajouter ou supprimer des règles eslint, ou de modifier le package.json global.

2024-06-20 12:58 UTC, Yoann-Fortin approved these changes

2024-06-20 12:58 UTC, merged