New fix kevin
WildCodeSchool-2024-02/JS-bdx-0224-P3-street_art_hunter pull request #52
Opened 2024-07-22 10:17 UTC by sorrento974

2024-07-22 12:39 UTC, Dinosaure7 commented on client/src/main.jsx
> -import AdminStreetArtPage from "./pages/AdminStreetArtPage";
Why do you delete this file import?
and the next.
Basically why delete all that is related to the street art page?

2024-07-22 13:29 UTC, Dinosaure7 commented on client/src/main.jsx
> -import AdminStreetArtPage from "./pages/AdminStreetArtPage";
Saw with Kevin, all good.

2024-07-22 13:29 UTC, Dinosaure7 approved these changes

2024-07-23 06:33 UTC, Yoann-Fortin requested changes

2024-07-23 06:33 UTC, Yoann-Fortin commented on client/src/pages/Login.jsx
> +          <div className="error-message">{actionData.error}</div>
A p tag will be better

2024-07-23 06:33 UTC, Yoann-Fortin commented on client/src/styles/ZoomControl.css
> +@media screen and (min-width: 380px) and (max-width: 410px) {
The css is cascaded, and working in mobile first, the min-width is not necessary.

2024-07-23 10:08 UTC, Yoann-Fortin approved these changes

2024-07-23 10:25 UTC, Yoann-Fortin approved these changes

2024-07-23 10:25 UTC, merged