Fix dev multiple fixes
WildCodeSchool-2024-02/JS-bdx-0224-P3-street_art_hunter pull request #55
Opened 2024-07-22 20:28 UTC by Alice-Berthelot

2024-07-22 20:35 UTC, sorrento974 approved these changes

2024-07-23 06:35 UTC, Yoann-Fortin requested changes

2024-07-23 06:35 UTC, Yoann-Fortin commented on client/src/pages/Contact.jsx
> +                <li
A p tag will be better

2024-07-23 07:58 UTC, Alice-Berthelot commented on client/src/pages/Contact.jsx
> +                <li
done

2024-07-23 10:06 UTC, Yoann-Fortin approved these changes

2024-07-23 10:06 UTC, merged