merge from dev to main
WildCodeSchool-2024-02/JS-bdx-0224-P3-street_art_hunter pull request #6
Opened 2024-06-20 12:24 UTC by sorrento974

2024-06-20 13:09 UTC, sorrento974 reviewed
c'es tout bon pour moi

2024-06-20 13:16 UTC, Dinosaure7 commented on client/index.html
All good!

2024-06-20 13:17 UTC, Dinosaure7 commented on client/postcss.config.js
Import of Tailwind OK!

2024-06-20 13:33 UTC, Dinosaure7 commented on client/src/components/NavBar.jsx
All good!

2024-06-20 13:40 UTC, Dinosaure7 commented on client/src/style/Home.css
Please delete this file since it is a duplicate of client/src/styles/Home.css. 
It is not used in another file either.

2024-06-20 13:45 UTC, Dinosaure7 commented on client/src/styles/NavBar.css
Quelques indentations et sauts de lignes à revoir

2024-06-20 13:49 UTC, Dinosaure7 commented on server/database/schema.sql
Great table work!

2024-06-20 13:51 UTC, Dinosaure7 commented on server/index.js
Only comments set up by WCS should be fine right.

2024-06-20 13:51 UTC, Dinosaure7 approved these changes

2024-06-20 13:51 UTC, Dinosaure7 commented
Pull request approved

2024-06-21 11:53 UTC, Alice-Berthelot approved these changes

2024-06-22 18:49 UTC, Delgorithm approved these changes

2024-06-24 13:48 UTC, Yoann-Fortin requested changes

2024-06-24 13:48 UTC, Yoann-Fortin commented on client/src/components/NavBar.jsx
> +            <p className="navText">Page d'accueil</p>
Incorrect use of the p tag

2024-06-24 13:48 UTC, Yoann-Fortin commented on client/src/pages/Home.jsx
> +    <section>
Incorrect use of the section tag

2024-06-24 13:48 UTC, Yoann-Fortin commented on package-lock.json
To delete please

2024-06-24 13:48 UTC, Yoann-Fortin commented on client/src/styles/NavBar.css
One codes on mobile first please

2024-06-25 09:58 UTC, Yoann-Fortin approved these changes

2024-06-25 09:58 UTC, merged